# Generated by Django 5.1.1 on 2024-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prix (optionnel)')),
                ('best_seller', models.BooleanField(default=False, verbose_name='Best-seller')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('categorie', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-fiction'), ('science_fiction', 'Science-fiction'), ('fantasy', 'Fantasy'), ('biography', 'Biographie'), ('history', 'Histoire'), ('mystery', 'Mystère'), ('poetry', 'Poésie'), ('policier', 'Policier')], max_length=50, verbose_name='Catégorie')),
                ('couverture', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'image de couverture")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
