# Generated by Django 5.1.1 on 2024-09-25 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('science_fiction', 'Science-fiction'), ('fantasy', 'Fantasy'), ('biography', 'Biographie'), ('history', 'Histoire'), ('mystery', 'Mystère'), ('poetry', 'Poésie'), ('policier', 'Policier')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='main.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
