# Generated by Django 5.1.1 on 2024-09-28 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
