# Generated by Django 5.1.1 on 2024-09-28 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_location_date_debut_alter_location_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
