# Generated by Django 5.1.1 on 2024-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_location_reminder_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=20),
        ),
    ]
