# Generated by Django 5.1.1 on 2024-10-04 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_messagetchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetchat',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
