# Generated by Django 5.1.1 on 2024-10-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_emailpromotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailPromotion',
        ),
    ]
